name: Build uYouEnhanced

on:
  workflow_dispatch:
    inputs:
      DECRYPTED_YOUTUBE_URL:
        description: "The *decrypted* YouTube ipa (Provide Direct Download Link)."
        default: ""
        required: true
        type: string
      UYOU_VERSION:
        description: "The version of uYou to inject (Provide Number)"
        default: "3.0.4"
        required: true
        type: string
      UYOUENHANCED_VERSION:
        description: "The version of uYouEnhanced to inject (Provide *FULL* SHA, Tag, or Branch)."
        default: "main"
        required: true
        type: string

jobs:
  build:
    name: Build uYouEnhanced
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    env:
      THEOS: ${{ github.workspace }}/theos

    steps:
      - name: 🛡️ Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - name: 🚚 Check out the Repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          repository: driftywinds/uYouEnhanced
          ref: ${{ inputs.uyouenhanced_version }}
          path: main
          submodules: recursive

      - name: 🛠️ Prepare YouTube IPA
        working-directory: ${{ github.workspace }}/main
        run: |
          wget "${{ inputs.DECRYPTED_YOUTUBE_URL }}" --no-verbose -O YouTube.ipa
          unzip -q YouTube.ipa

          echo "YOUTUBE_VERSION=$(defaults read "$(pwd)/Payload/YouTube.app/Info" CFBundleVersion)" >> $GITHUB_ENV

      - name: 💾 Install System Dependencies
        run: sudo apt install libplist-utils

      - name: 🔍 Check cache
        run: echo upstream_heads=`git ls-remote https://github.com/theos/theos | head -n 1 | cut -f 1`-`git ls-remote https://github.com/theos/sdks | head -n 1 | cut -f 1`-`git ls-remote https://github.com/kabiroberai/swift-toolchain-linux | head -n 1 | cut -f 1` >> $GITHUB_ENV

      - name: ♻️ Restore cache if available
        id: cache
        uses: actions/cache/restore@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: ${{ github.workspace }}/theos
          key: ${{ env.upstream_heads }}

      - name: ⚙️ Setup Theos
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          repository: theos/theos
          path: theos
          submodules: recursive

      - name: ⚙️ Setup iOS SDK
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          repository: theos/sdks
          path: theos/sdks
          sparse-checkout: "iPhoneOS16.5.sdk"
          sparse-checkout-cone-mode: false

      - name: ⚙️ Setup iOS Swift Toolchain
        if: steps.cache.outputs.cache-hit != 'true'
        run: wget -qO- https://github.com/kabiroberai/swift-toolchain-linux/releases/download/v2.3.0/swift-5.8-ubuntu22.04.tar.xz | tar -xJC $THEOS/toolchain/
          
      - name: ♻️ Save cache if needed
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: ${{ github.workspace }}/theos
          key: ${{ env.upstream_heads }}

      - name: ⚙️ Setup Theos Jailed
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          repository: Mukul1127/theos-jailed
          path: theos-jailed
          submodules: true

      - name: 💾 Install Theos Jailed
        working-directory: theos-jailed
        run: ./install

      - name: 📦 Build IPA
        working-directory: main
        run: |
          make package YOUTUBE_VERSION=${{ env.YOUTUBE_VERSION }} UYOU_VERSION=${{ inputs.UYOU_VERSION }} IPA=Payload/YouTube.app FINALPACKAGE=1

      - name: 🚀 Publish Draft Release
        uses: softprops/action-gh-release@a74c6b72af54cfa997e81df42d94703d6313a2d0 # v2.0.6
        with:
          tag_name: (v${{ env.YOUTUBE_VERSION }})-(${{ inputs.UYOU_VERSION }})-(${{ inputs.UYOUENHANCED_VERSION }})-(${{ github.run_number }})
          files: main/packages/*.ipa
          draft: true
