name: Build uYouEnhanced

on:
  workflow_dispatch:
    inputs:
      decrypted_youtube_url:
        description: "The *decrypted* YouTube ipa (Provide Direct Download Link)."
        default: ""
        required: true
        type: string
      uyou_version:
        description: "The version of uYou to inject (Provide Number)"
        default: "3.0.3"
        required: true
        type: string
      uyouenhanced_version:
        description: "The version of uYouEnhanced to inject (Provide *FULL* SHA, Tag, or Branch)."
        default: "main"
        required: true
        type: string

jobs:
  build:
    name: Build uYouEnhanced
    runs-on: macos-latest
    permissions:
      contents: write
    env:
      THEOS: ${{ github.workspace }}/theos

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.6
        with:
          repository: arichornlover/uYouEnhanced
          ref: ${{ inputs.uyouenhanced_version }}
          path: main
          submodules: recursive

      - name: Prepare YouTube IPA
        working-directory: ${{ github.workspace }}/main
        id: prepare_youtube
        run: |
          wget "${{ inputs.decrypted_youtube_url }}" -O YouTube.ipa
          unzip -q YouTube.ipa
          youtube_version=$(defaults read "$(pwd)/Payload/YouTube.app/Info" CFBundleVersion)
          sed -i "" "17s#.*#YOUTUBE_VERSION = ${youtube_version}#g" Makefile
          echo "youtube_version=${youtube_version}" >> $GITHUB_OUTPUT
    
      - name: Install Dependencies
        run: brew install ldid make

      - name: Check cache
        run: |
          echo upstream_heads=`git ls-remote https://github.com/theos/theos | head -n 1 | cut -f 1`-`git ls-remote https://github.com/arichornlover/sdks | head -n 1 | cut -f 1` >> $GITHUB_ENV

      - name: Restore cache if available
        id: cache
        uses: actions/cache/restore@v4.0.2
        with:
          path: ${{ github.workspace }}/theos
          key: ${{ env.upstream_heads }}

      - name: Setup Theos
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v4.1.6
        with:
          repository: theos/theos
          path: theos
          submodules: recursive

      - name: Setup iOS SDK
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v4.1.6
        with:
          repository: arichornlover/sdks
          path: theos/sdks
          sparse-checkout: "iPhoneOS17.0.3.sdk"
          sparse-checkout-cone-mode: false

      - name: Save cache if available
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4.0.2
        with:
          path: ${{ github.workspace }}/theos
          key: ${{ env.upstream_heads }}

      - name: Setup Theos Jailed
        uses: actions/checkout@v4.1.6
        with:
          repository: Mukul1127/theos-jailed
          path: theos-jailed
          submodules: recursive

      - name: Install Theos Jailed
        working-directory: ${{ github.workspace }}/theos-jailed
        run: |
          ./install

      - name: Fix Compilation
        working-directory: ${{ github.workspace }}/main
        run: |
          mkdir -p ${{ github.workspace }}/theos/lib/iphone/rootless
          sed -i '' "1s#.*#export TARGET = iphone:clang:latest:14.0#g" Makefile
          sed -i '' "1s#.*#TARGET := iphone:clang:latest:14.0#g" Tweaks/YTHoldForSpeed/Makefile
          
      - name: Build Package
        working-directory: ${{ github.workspace }}/main
        run: |
          gmake package THEOS_PACKAGE_SCHEME=rootless IPA=Payload/YouTube.app FINALPACKAGE=1

      - name: Create Draft Release
        uses: softprops/action-gh-release@v2.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YOUTUBE_VERSION: ${{ steps.prepare_youtube.outputs.youtube_version }}
          UYOU_VERSION: ${{ inputs.uyou_version }}
          UYOUENHANCED_VERSION: ${{ inputs.uyouenhanced_version }}
        with:
          tag_name: (v${{ env.YOUTUBE_VERSION }})-(${{ env.UYOU_VERSION }})-(${{ env.UYOUENHANCED_VERSION }})-(${{ github.run_number }})
          name: (v${{ env.YOUTUBE_VERSION }})-(${{ env.UYOU_VERSION }})-(${{ env.UYOUENHANCED_VERSION }})-(${{ github.run_number }})
          files: main/packages/*.ipa
          draft: true
