name: Build uYouEnhanced

on:
  workflow_dispatch:
    inputs:
      uyou_version:
        description: "The version of uYou"
        default: "3.0.3"
        required: true
        type: string
      uyouenhanced_version:
        description: "The version of uYouEnhanced (*FULL* SHA, Tag, or Branch)"
        default: "main"
        required: true
        type: string
      decrypted_youtube_url:
        description: "The direct download link to the *decrypted* YouTube ipa"
        default: ""
        required: true
        type: string

jobs:
  build:
    name: Build uYouEnhanced
    runs-on: macos-latest

    steps:
      - name: Install Dependencies
        run: brew install ldid make

      - name: Check cache
        run: |
          echo upstream_heads=`git ls-remote https://github.com/theos/theos | head -n 1 | cut -f 1`-`git ls-remote https://github.com/arichornlover/sdks | head -n 1 | cut -f 1` >> $GITHUB_ENV

      - name: Use cache
        id: cache
        uses: actions/cache@v4.0.2
        with:
          path: ~/theos
          key: ${{ env.upstream_heads }}

      - name: Setup Theos
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v4.1.1
        with:
          repository: theos/theos
          path: theos
          submodules: recursive

      - name: Setup iOS SDK
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/checkout@v4.1.1
        with:
          repository: arichornlover/sdks
          path: theos/sdks
          sparse-checkout: "iPhoneOS16.4.sdk"
          sparse-checkout-cone-mode: false

      - name: Set Theos Environment Variable
        run: |
          echo "THEOS=${{ github.workspace }}/theos" >> $GITHUB_ENV

      - name: Setup Theos Jailed
        uses: actions/checkout@v4.1.1
        with:
          repository: qnblackcat/theos-jailed
          path: theos-jailed
          submodules: recursive

      - name: Install Theos Jailed
        run: |
          ./theos-jailed/install
    
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1
        with:
          repository: arichornlover/uYouEnhanced
          ref: ${{ inputs.uyouenhanced_version }}
          path: main
          submodules: recursive

      - name: Prepare YouTube IPA
        id: prepare_youtube
        run: |
          cd ${{ github.workspace }}/main
          wget "${{ inputs.decrypted_youtube_url }}" -O YouTube.ipa
          unzip -q YouTube.ipa
          youtube_version=$(defaults read "$(pwd)/Payload/YouTube.app/Info" CFBundleVersion)
          sed -i "" "17s#.*#YOUTUBE_VERSION = ${youtube_version}#g" Makefile
          echo "youtube_version=${youtube_version}" >> $GITHUB_OUTPUT
          
      - name: Build Package
        run: |
          cd ${{ github.workspace }}/main
          gmake package THEOS_PACKAGE_SCHEME=rootless IPA=Payload/YouTube.app FINALPACKAGE=1

      - name: Create Draft Release
        uses: softprops/action-gh-release@v2.0.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UYOU_VERSION: ${{ inputs.uyou_version }}
          YOUTUBE_VERSION: ${{ steps.prepare_youtube.outputs.youtube_version }}
        with:
          tag_name: v${{ env.YOUTUBE_VERSION }}-${{ env.UYOU_VERSION }}-(${{ github.run_number }})
          name: v${{ env.YOUTUBE_VERSION }}-${{ env.UYOU_VERSION }}-(${{ github.run_number }})
          files: main/packages/*.ipa
          draft: true
