name: Build uYouEnhanced

on:
  workflow_dispatch:
    inputs:
      uyou_version:
        description: "The version of uYou"
        default: "3.0.3"
        required: true
        type: string
      uyouenhanced_version:
        description: "The version of uYouEnhanced (Commit ID or Branch)"
        default: "main"
        required: true
        type: string
      decrypted_youtube_url:
        description: "The direct download link to the decrypted YouTube ipa"
        default: ""
        required: true
        type: string

jobs:
  build:
    name: Build uYouEnhanced
    runs-on: macos-latest

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4.1.1
        with:
          repository: arichornlover/uYouEnhanced
          ref: ${{ inputs.uyouenhanced_version }}
          path: main
          submodules: recursive

      - name: Install Dependencies
        run: brew install ldid dpkg make

      - name: Setup Theos
        uses: actions/checkout@v4.1.1
        with:
          repository: theos/theos
          path: theos
          submodules: recursive
      
      - name: SDK Caching
        id: SDK
        uses: actions/cache@v4.0.2
        env:
          cache-name: iOS-${{ inputs.sdk_version }}-SDK
        with:
          path: theos/sdks/
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}

      - name: Download iOS SDK
        if: steps.SDK.outputs.cache-hit != 'true'
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/xybp888/iOS-SDKs
          cd sdks
          git sparse-checkout set --no-cone iPhoneOS14.0.sdk
          git checkout
          mv *.sdk $THEOS/sdks
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Setup Theos Jailed
        uses: actions/checkout@v4.1.1
        with:
          repository: qnblackcat/theos-jailed
          path: theos-jailed
          submodules: recursive

      - name: Install Theos Jailed
        run: |
          ./theos-jailed/install
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Prepare YouTube iPA
        id: prepare_youtube
        run: |
          wget "$YOUTUBE_URL" --no-verbose -O main/YouTube.ipa
          cd ${{ github.workspace }}/main
          mv YouTube.ipa YouTube.zip
          unzip -q YouTube.zip
          youtube_version=$(defaults read "$(pwd)/Payload/YouTube.app/Info" CFBundleVersion)
          echo "==> YouTube v$youtube_version downloaded!"
          sed -i '' "17s#.*#YOUTUBE_VERSION = ${youtube_version}#g" Makefile
          echo "youtube_version=${youtube_version}" >> $GITHUB_OUTPUT
        env:
          THEOS: ${{ github.workspace }}/theos
          YOUTUBE_URL: ${{ inputs.decrypted_youtube_url }}

      - name: Build Package
        id: build_package
        run: |
          cd ${{ github.workspace }}/main
          gmake package THEOS_PACKAGE_SCHEME=rootless IPA=Payload/YouTube.app FINALPACKAGE=1
          echo "package=$(ls -t packages | head -n1)" >>$GITHUB_OUTPUT
          echo -e "==> \033[1mSHASUM256: $(shasum -a 256 packages/*.ipa | cut -f1 -d' ')\033[0m"

      - name: Upload Artifact
        if: ${{ inputs.upload_artifact }}
        uses: actions/upload-artifact@v4.3.1
        env:
          UYOU_VERSION: ${{ inputs.uyou_version }}
          YOUTUBE_VERSION: ${{ steps.prepare_youtube.outputs.youtube_version }}
        with:
          name: uYouEnhanced_${{ env.YOUTUBE_VERSION }}_${{ env.UYOU_VERSION }}
          path: ${{ github.workspace }}/main/packages/${{ steps.build_package.outputs.package }}
          if-no-files-found: error
